#! /bin/bash

#find the photodiode directory with help_num as an input argument
help_num=$helper_num
SYSFS_ADC_DIR="/sys/devices/ocp.3/helper."$help_num"/AIN0"

#find and touch the file_name that it will output to it
file1=$file_name
echo $file1
echo $file_name
touch $file1

#set up averaging variables
toAverage=25
average=0
rms=0
count=0

#set trigger level to loop over
Trigger3="/sys/class/gpio/gpio46"
trig3=`cat "$Trigger3/value"`

#always loops while trigger3 is activated
while (( $trig3 == 1 )); do
	
	  #gets the value of trigger3 from the directory
	  trig3=`cat "$Trigger3/value"`
	  total=0
	  
	  #finds the voltage from the photodiode and reads 25 times
	  for i in {0 .. 24}; do
	  	  adc=`cat "$SYSFS_ADC_DIR"`
		  volts[$i]=$adc
		  total=$(( $total + $adc ))
		  sleep 0.02
	  done
	  
	  #finds the average from the total voltage read over 25 times
	  averages=`./divide $total $toAverage`

	  #finds the error on the mean for the voltage
	  rmsSum=0
	  k=0
	  for k in {0 .. 24}; do
		  rmsSum=$(( $rmsSum + `./foil ${volts[$k]} averages`))
	  done
	  rms=`./find_error $rmsSum $toAverage`
	  
	  #reads the values out to the file_name
	  echo $count" "$averages" "$rms >> $file_name

	  #increments the time count
	  count=$(( $count + 0.5 ))
done
